// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	FORWARD_TO_ADDRESS: string;
	EMAIL_PREFIX: string;
	TLD_TAG: { [key: string]: string };
	ADDRESS_TAG: { [key: string]: string };
	DISCORD_CLIENT_ID: string;
	DISCORD_GUILD_ID: string;
	DISCORD_CHANNEL_ID: string;
	DISCORD_EMBED_LIMIT: 4096;
	DISCORD_FILE_LIMIT: 8000000;
	RESEND_API_KEY: string;
	DISCORD_BOT_TOKEN: string;
	DISCORD_PUBLIC_KEY: string;
	DB: D1Database;
}
